# fly.toml app configuration file generated for warriorglow on 2023-10-30T21:29:12+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "warriorglow"
primary_region = "jnb"

[build]

[http_service]
  internal_port = 5000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
